=== dionyziz/blogcube/etc/database/blogcubedb.dtd
<!ELEMENT blogcube (database*)>
<!ATTLIST blogcube version CDATA #REQUIRED>
<!ATTLIST blogcube codename CDATA #IMPLIED>

<!ELEMENT database (table*)>
<!ATTLIST database name CDATA #REQUIRED>
<!ATTLIST database type CDATA #FIXED "MySQL">

<!ELEMENT table (field*)>
<!ATTLIST table name CDATA #REQUIRED>
<!ATTLIST table type (MyISAM|InnoDB) "MyISAM">

<!ELEMENT field EMPTY>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field type (INT|TEXT|LONGTEXT|ENUM|DATE|DATETIME|TIMESTAMP) "INT">
<!ATTLIST field values CDATA #IMPLIED>
<!ATTLIST field autoincrement (yes|no) "no">
<!ATTLIST field primarykey (yes|no) "no">
<!ATTLIST field ref CDATA #IMPLIED>

=== dionyziz/blogcube/etc/database/database.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xml2sql.xsl"?>
<!DOCTYPE blogcube SYSTEM "blogcubedb.dtd">
<blogcube version="2.0" codename="Paris">
	<database name="blogcube" type="MySQL">
		<table name="users">
			<field name="user_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="user_username" type="TEXT" />
			<field name="user_password" type="TEXT" /> <!-- md5 -->
			<field name="user_failedlogins" type="INT" />
			<field name="user_pin" type="TEXT" /> <!-- md5 -->
			<field name="user_lastactive" type="DATETIME" />
			<field name="user_invitedbyuserid" type="INT" />
			<field name="user_invitationsleft" type="INT" />
			<field name="user_friendsrootfolderid" type="INT" ref="friendfolders.ffolder_id" />
			<field name="user_bookmarksrootfolderid" type="INT" ref="bookmarkfolders.bfolder_id" />
			<field name="user_email" type="TEXT" />
			<field name="user_mobilephone" type="TEXT" />
			<field name="user_defaultavatar" type="INT" ref="media.media_id" /> <!-- Notice: No reference to `avatars`, but `media` -->
			<field name="user_bcadmin" type="INT" /> <!-- 100 = user ; 500 = admin ; 1000 = lead developer -->
			<field name="user_registerdate" type="TIMESTAMP" />
			<field name="user_allowemailblogging" type="ENUM" values="'yes','no'" />
			<field name="user_allowsmsblogging" type="ENUM" values="'yes','no'" />
			<!-- <field name="user_timezone" type="INT" /> -->

			<!-- <Personal Details> -->
			<field name="user_firstname" type="TEXT" />
			<field name="user_lastname" type="TEXT" />
			<field name="user_countryid" type="INT" ref="countries.country_id" />
			<field name="user_gender" type="ENUM" values="'male','female'" />
			<field name="user_dob" type="DATE" />
			<field name="user_website" type="TEXT" />
			<field name="user_msn" type="TEXT" />
			<field name="user_yahoo" type="TEXT" />
			<field name="user_icq" type="TEXT" />
			<field name="user_jabber" type="TEXT" />
			<field name="user_gtalk" type="TEXT" />
			<field name="user_aim" type="TEXT" />
			<!-- </Personal Details> -->
			
			<!-- <Publicize> -->
			<field name="user_publicemail" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicmsn" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicyahoo" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicicq" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicjabber" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicgtalk" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicaim" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicbirthday" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicage" type="ENUM" values="'private','friends','ffriends','public'" />
			<field name="user_publicmobile" type="ENUM" values="'private','friends','ffriends','public'" />
			<!-- </Publicize> -->
			<field name="user_favoritemovie" type="TEXT" />
			<field name="user_favoriteband" type="TEXT" />
			<field name="user_favoritemusicgenre" type="TEXT" />
			<field name="user_favoritegame" type="TEXT" />
			<field name="user_favoritequote" type="TEXT" />
			<field name="user_hair" type="ENUM" values="'','blonde','brown','black','red','ginger','auburn','gray'" />
			<field name="user_eyes" type="ENUM" values="'','blue','brown','green','hazel','gray'" />
			<field name="user_aboutme" type="TEXT" />
		</table>
		<table name="useravatars">
			<field name="avatar_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="avatar_userid" type="INT" ref="users.user_id" />
			<field name="avatar_mediaid" type="INT" ref="media.media_id" />
		</table>
		<table name="blogs">
			<field name="blog_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="blog_active" type="ENUM" values="'yes','no'" />
			<field name="blog_name" type="TEXT" /> <!-- unique -->
			<field name="blog_title" type="TEXT" />
			<field name="blog_description" type="TEXT" />
			<field name="blog_access" type="ENUM" values="'private','friends','public'" />
			<field name="blog_createdate" type="DATETIME" />
			<field name="blog_templateid" type="INT" ref="templates.template_id" />
            <field name="blog_popularity" type="INT" /><!-- popularity of blog; we should find a method to evaluate it; always 0 for now -->
		</table>
		<table name="permissions">
			<field name="permission_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="permission_userid" type="INT" ref="users.user_id" />
			<field name="permission_blogid" type="INT" ref="blogs.blog_id" />
			<field name="permission_permissions" type="INT" />
		</table>
		<table name="posts">
			<field name="post_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="post_blogid" type="INT" ref="blogs.blog_id" />
			<field name="post_userid" type="INT" ref="users.user_id" />
			<field name="post_title" type="TEXT" />
			<field name="post_text" type="TEXT" />
			<field name="post_date" type="DATETIME" />
			<field name="post_ip" type="TEXT" />
			<field name="post_active" type="ENUM" values="'yes','no'" />
		</table>
		<table name="templates"> <!-- Needs to be reconsidered -->
			<field name="template_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="template_title" type="TEXT" />
			<field name="template_createdate" type="DATETIME" />
			<field name="template_lastmodified" type="DATETIME" />
			<field name="template_bodybd" type="TEXT" />
			<field name="template_bodyalign" type="ENUM" values="'center','left','right'" />
			<field name="template_bodyrightbg" type="TEXT" />
			<field name="template_bodyleftbf" type="TEXT" />
			<field name="template_titlebgimg" type="TEXT" />
			<field name="template_titlebg" type="TEXT" />
		</table>
		<table name="countries">
			<field name="country_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="country_name" type="TEXT" />
			<field name="country_flagmediaid" type="INT" ref="media.media_id" /> <!-- image -->
		</table>
		<table name="invitations">
			<field name="invitation_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="invitation_invitinguserid" type="INT" ref="users.user_id" />
			<field name="invitation_invitedemail" type="TEXT" />
			<field name="invitation_invitedname" type="TEXT" />
			<field name="invitation_registereduserid" type="INT" ref="users.user_id" />
			<field name="invitation_code" type="TEXT" /> <!-- random md5 -->
		</table>
		<!-- <Friends> -->
		<table name="friendfolders">
			<field name="ffolder_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="ffolder_parentfolderid" type="INT" ref="friendfolders.ffolder_id" /> <!-- if it's a root folder, this is 0 -->
			<field name="ffolder_name" type="TEXT" />
			<field name="ffolder_userid" type="INT" />
			<field name="ffolder_expanded" type="ENUM" values="'no','yes'" />
		</table>
		<table name="friends">
			<field name="friend_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="friend_userid" type="INT" ref="users.user_id" />
			<field name="friend_parentfolderid" type="INT" ref="friendfolders.ffolder_id" /> <!-- can't be 0 -->
			<field name="friend_dateadded" type="DATETIME"/>
		</table>
		<!-- </Friends> -->
		
		<!-- <Bugreporting> -->
		<table name="bugs">
			<field name="bug_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="bug_name" type="TEXT" />
			<field name="bug_description" type="TEXT" />
			<field name="bug_os" type="TEXT" />
			<field name="bug_userip" type="TEXT" />
			<field name="bug_userid" type="INT" ref="users.user_id" />
			<field name="bug_userbrowser" type="TEXT" />
			<field name="bug_userbrowserversion" type="TEXT" />
			<field name="bug_fixedby" type="INT" ref="users.user_id" />
			<field name="bug_useragent" type="TEXT" />
			<field name="bug_osversion" type="TEXT" />
			<field name="bug_date" type="DATETIME" />
			<field name="bug_status" type="ENUM" values="'new','fixed','duplicate','invalid'"/>
			<field name="bug_assigned" type="INT" />
		</table>
		<!--</Bugreporting>-->
		
		<!--<Action logging>-->
		<table name="logs" type="MyISAM"> <!-- MyISAM necessary for INSERT DELAYED -->
			<field name="log_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="log_userid" type="INT" ref="users.user_id" />
			<field name="log_ip" type="TEXT" />
			<field name="log_timestamp" type="TIMESTAMP" />
			<field name="log_action" type="TEXT" />
		</table>
		
		<table name="errorlogs">
			<field name="err_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="err_userid" type="INT" ref="users.user_id" />
			<field name="err_description" type="TEXT" />
			<field name="err_ip" type="TEXT" />
			<field name="err_timestamp" type="TIMESTAMP" />
			<field name="err_page" type="TEXT" />
		</table>
		<!--</Action logging>-->
		
		<!--<Media>-->
		<table name="media">
			<field name="media_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="media_ip" type="TEXT" />
			<field name="media_timestamp" type="TIMESTAMP" />
			<field name="media_userid" type="INT" ref="users.user_id" />
			<field name="media_filename" type="TEXT" />
			<field name="media_mimetype" type="TEXT" />
			<field name="media_compressed" type="ENUM" values="'no','yes'" />
		</table>
		<!--<Deleted media>-->
		<table name="deleted_media">
			<field name="del_id" type="INT" autoincrement="yes" primarykey="yes" />
			<field name="del_mediaid" type="INT" ref="media.media_id" />
			<field name="del_ip_upload" type="TEXT" />
